// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3F43UbwVslZ6jTK-Vxkxrx-W8478K4pE',
    appId: '1:440085729678:web:09b801fc160dcce00494df',
    messagingSenderId: '440085729678',
    projectId: 'hamrodokan-12f2a',
    authDomain: 'hamrodokan-12f2a.firebaseapp.com',
    storageBucket: 'hamrodokan-12f2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQUzCo8urosJoLOq6DDqn9D3kZxyebEo',
    appId: '1:440085729678:android:58c16ae16091fd350494df',
    messagingSenderId: '440085729678',
    projectId: 'hamrodokan-12f2a',
    storageBucket: 'hamrodokan-12f2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNY-KQK2y-gzwGNR7a2YnBS4pvMTV3KH0',
    appId: '1:440085729678:ios:c9c8ec4affd220a30494df',
    messagingSenderId: '440085729678',
    projectId: 'hamrodokan-12f2a',
    storageBucket: 'hamrodokan-12f2a.appspot.com',
    iosBundleId: 'com.example.hmrodokan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNY-KQK2y-gzwGNR7a2YnBS4pvMTV3KH0',
    appId: '1:440085729678:ios:d5463b3d4e2130710494df',
    messagingSenderId: '440085729678',
    projectId: 'hamrodokan-12f2a',
    storageBucket: 'hamrodokan-12f2a.appspot.com',
    iosBundleId: 'com.example.hmrodokan.RunnerTests',
  );
}
